### ISSUE TITLE
Blender 3.6 support for the add-on

### ISSUE THREAD

**Issue by julscloudops** [inca/blender-differential-growth#15]
Hello!

I love this add-on and wanted to use it on Blender 3.6 with Simulation Nodes, do you know if it's supported or was a breaking change introduced?

I tried to get it to work but I was receiving this error when triggering the Differential Growth ( I made sure to create a vertex group before triggering it):

`Python: Traceback (most recent call last):
  File "C:\Users\jcamp\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-differential-growth-2-1-1\op_grow.py", line 22, in execute
    grow_step(
  File "C:\Users\jcamp\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-differential-growth-2-1-1\op_grow.py", line 52, in grow_step
    w = get_vertex_weight(bm, vert, group_index)
  File "C:\Users\jcamp\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-differential-growth-2-1-1\op_grow.py", line 111, in get_vertex_weight
    weights = vert[weight_layer]
AttributeError: BMElem[key]: invalid key, must be a BMLayerItem` 

Kind regards.

**Comment by inca** [comment]
Hey, this usually happens when you try it in Edit mode. Try using it in Object or Weight Paint mode.
